name: serverpod_auth_sms_core_server
description: Server-side core for SMS registration and code login in Serverpod.
version: 0.1.0
repository: https://github.com/Metaildust/serverpod_auth_sms
homepage: https://pub.dev/packages/serverpod_auth_sms_core_server

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  serverpod: 3.2.3
  serverpod_auth_idp_server: 3.2.3
