name: serverpod_auth_sms_crypto_server
description: Hash + decryptable phone storage for Serverpod SMS auth.
version: 0.1.5
repository: https://github.com/Metaildust/serverpod_auth_sms
homepage: https://pub.dev/packages/serverpod_auth_sms_crypto_server

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.7
  cryptography: ^2.9.0
  serverpod: ^3.2.3
  serverpod_auth_core_server: ^3.2.3
  serverpod_auth_idp_server: ^3.2.3
  serverpod_auth_sms_core_server: ^0.1.0

dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.1
