name: serverpod_auth_sms_hash_client
description: Client for serverpod_auth_sms_hash.
version: 0.1.5
repository: https://github.com/Metaildust/serverpod_auth_sms
homepage: https://pub.dev/packages/serverpod_auth_sms_hash_client

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  serverpod_auth_core_client: ^3.2.3
  serverpod_auth_idp_client: ^3.2.3
  serverpod_auth_sms_core_client: ^0.1.0
  serverpod_client: ^3.2.3

dev_dependencies:
  test: ^1.25.0
  lints: ^5.1.1
